spring:
  kafka:
    consumer:
      group-id: midas-core
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest                  # <— start from beginning if no commit
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.jpmc.midascore.foundation.Transaction
        spring.json.use.type.headers: false        # <— rely on the default type
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    listener:
      missing-topics-fatal: false

general:
  kafka-topic: test-topic
